- .gitattributes
- Build.ps1
- README.md
- appveyor.yml
- global.json
- sample/Sample/Program.cs
- sample/Sample/Sample.xproj
- sample/Sample/appsettings.json
- sample/Sample/project.json
- sample/Sample/project.lock.json
- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.xproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/project.json
- src/Serilog.Settings.Configuration/project.lock.json
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.xproj
- test/Serilog.Settings.Configuration.Tests/project.json
- test/Serilog.Settings.Configuration.Tests/project.lock.json
A few changes here and there. `DependencyManager` seems to do the job of `ILibraryManager` well enough, but doesn't list assemblies that aren't directly referenced by the code, so loading based on the package name is necessary.
.NET 4.x now seems to need a build flag to preserve this info, so that's mentioned in the README.
> RC2 Update

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
IConfiguration.GetSection(..) doesn't return null if section is not defined. With MinimumLevel we should check it's Value property.
> Read from config should not throw if MinimumLevel is not defined in settings file

- Build.ps1
- sample/Sample/project.lock.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/project.json
- src/Serilog.Settings.Configuration/project.lock.json
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/DummyLoggerConfigurationExtensions.cs
- test/Serilog.Settings.Configuration.Tests/project.json
- test/Serilog.Settings.Configuration.Tests/project.lock.json
Not absolute parameter count. Corresponds to https://github.com/serilog/serilog/issues/798.
Also removes a spurious _Newtonsoft.Json_ dependency and fixes some test infrastructure issues in order to get it all building.
> Choose overloads based on matching parameter count

- sample/Sample/Program.cs
- sample/Sample/appsettings.json
- sample/Sample/project.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- fixes [#32](https://github.com/serilog/serilog-settings-configuration/issues/32)
- some cleanup/unification around surrogate configuration methods
With the help of the greatest `Serilog.Filters.Expressions` will support these kinds of configurations:
```json
"Filter": [
{
"Name": "ByIncludingOnly",
"Args": {
"expression": "Application = 'Sample'"
}
},
{
"Name": "With",
"Args": {
"filter": "Sample.CustomFilter, Sample"
}
}
],
```
> Filter support 

- sample/Sample/Sample.csproj
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationSectionArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/IConfigurationArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/IConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
- fixes [#37](https://github.com/serilog/serilog-settings-configuration/issues/37)
- adds `Serilog.Sinks.Async` support
- adds `LoggingLevelSwitch` parameter type support
Basically implementation based on converters around `Action<TSerilogConfiguration>` parameter types from configuration extensions methods.
> Configure sub-loggers through JSON appsettings

- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/Serilog.Settings.Configuration.Tests/Support/JsonStringConfigSource.cs
- fixes [#47](https://github.com/serilog/serilog-settings-configuration/issues/47)
- fixes [#23](https://github.com/serilog/serilog-settings-configuration/issues/23)
#23 is a side effect of fixing #47 (as already pointed out in previous [pr](https://github.com/serilog/serilog-settings-configuration/pull/28) that syntax was already supported by the `Microsoft.Extensions.Configuration`. Fixing #47 just enables it.)
> Fix #47, #23 [multiple sinks of the same kind; environment-friendly syntax)

- serilog-settings-configuration.sln
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/Serilog.Settings.Configuration.Tests/Support/ConfigurationBuilderExtensions.cs
- test/Serilog.Settings.Configuration.Tests/Support/CustomConsoleTheme.cs
- test/Serilog.Settings.Configuration.Tests/Support/DelegatingSink.cs
- test/Serilog.Settings.Configuration.Tests/Support/Extensions.cs
- test/Serilog.Settings.Configuration.Tests/Support/Some.cs
- test/TestDummies/Console/DummyConsoleSink.cs
- test/TestDummies/Console/Themes/ConcreteConsoleTheme.cs
- test/TestDummies/Console/Themes/ConsoleTheme.cs
- test/TestDummies/Console/Themes/ConsoleThemes.cs
- test/TestDummies/Console/Themes/EmptyConsoleTheme.cs
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
- test/TestDummies/DummyRollingFileAuditSink.cs
- test/TestDummies/DummyRollingFileSink.cs
- test/TestDummies/DummyThreadIdEnricher.cs
- test/TestDummies/DummyWithLevelSwitchSink.cs
- test/TestDummies/DummyWrappingSink.cs
- test/TestDummies/Properties/AssemblyInfo.cs
- test/TestDummies/TestDummies.csproj
Fixes #80
- handles AuditTo
- adds more general tests with sample json config snippets
- update Serilog reference to v2.5.à
> Support AuditTo in configuration

- .editorconfig
- serilog-settings-configuration.sln
- serilog-settings-configuration.sln.DotSettings
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationSectionArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/IConfigurationArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/IConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/LevelSwitchDictionaryExtensions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
fixes #69 
Supports : 
- declaration of LoggingLevelSwitch 
- MinimumLevel.ControlledBy(switch)
- MinimumLevel.Override(prefix, switch)
- passing a switch by reference as the argument to a Sink (or any callable method)
JSON syntax : 
```json
{
"Serilog": {
"Using": [ "TestDummies" ],
"LevelSwitches": { "$mySwitch": "Warning" },
"MinimumLevel": {
"ControlledBy": "$mySwitch"
},
"WriteTo": [
{
"Name": "DummyWithLevelSwitch",
"Args": {
"controlLevelSwitch": "$mySwitch"
}
}
]
}
}
```
but also overrides : 
```json
{
"Serilog": {
"Using": [ "TestDummies" ],
"LevelSwitches": { "$mySwitch": "Warning" },
"MinimumLevel": {
"Default": "Information",
"Override": {
"Microsoft": "$mySwitch"
}
},
"WriteTo": [
{
"Name": "DummyWithLevelSwitch",
"Args": {
"controlLevelSwitch": "$mySwitch"
}
}
]
}
}
```
In …
> Add support for LoggingLevelSwitch

- sample/Sample/Sample.csproj
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationValueSyntax.cs
Tactical fix for master, will need to come back onto dev.
> Fix #91 - wrong parameter name on surrogate WriteTo.Logger configuration method

- README.md
because [serilog-sinks-literate is being retired](https://github.com/serilog/serilog-sinks-literate#this-package-is-being-retired).
> Use `Console` instead of `LiterateConsole` in README

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
Throws `InvalidOperationException` if multiple configuration sources results in an ambiguous argument value. See #103 for details.
> Multiple value exception, fixes #103

- README.md
- sample/Sample/Program.cs
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
Added support for destructure `With` and max-limit settings, also opening up destructuring features to additional configuration through extension methods in other packages, as discussed in #106.
- ConfigurationReader:
- add ApplyDestructuring
- add FindDestructureConfigurationMethods
- added surrogates for several destructure config methods
- add comments explaining method-level surrogates
- renamed FindConfigurationMethods to FindConfigurationExtensions
- three unit tests modeled on Serilog's own destructure tests
- README updated with a few lines of JSON demonstrating the settings
- changes to sample program
- config for Destructure max string length and max collection depth
- log events to demonstrate Destructure config
- comment explaining Filter syntax is from S.F.Expressions package …
> Destructure support

- sample/Sample/Program.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/SurrogateConfigurationMethods.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
- test/TestDummies/DummyHardCodedStringDestructuringPolicy.cs
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
Fixes #115 
- Support method arguments of type `Type` by converting from the type's qualified name
- Add support for (non-extension) method `Destructure.AsScalar`
- Add test to check that custom extension methods `Destructure.XXX()` can properly be invoked
- Refactor `ConfigurationReader` by extracting all the *surrogate method* handling to a separate class
> Add support for .Destructure.AsScalar(Type scalarType) 

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
This will be resolved by NuGet for .NET Framework 4.6.1 upward, and is equivalent to the netstandard2.0 package version.
Fixes #123.
> Build a package version for net461

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
Per #111 method argument matching should be case-insensitive.
Note if there are questions or feedback, I am on vacation and won't be online again until Sept 5 earliest.
> fixes #111 - case-insensitive method argument-matching

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/SurrogateConfigurationMethods.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/TestDummies/DummyAnonymousUserFilter.cs
- test/TestDummies/DummyRollingFileAuditSink.cs
- test/TestDummies/DummyRollingFileSink.cs
- test/TestDummies/DummyThreadIdEnricher.cs
- test/TestDummies/DummyWrappingSink.cs
fixes #121 (similar to the work done in the core repo in serilog/serilog#1194 )
It adds support and tests for : 
- `WriteTo.Sink(ILogEventSink logEventSink, LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum, LoggingLevelSwitch levelSwitch = null)`
- `AuditTo.Sink(ILogEventSink logEventSink, LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum, LoggingLevelSwitch levelSwitch = null)`
- `Enrich.With(params ILogEventEnricher[] enrichers)` (with surrogate `Enrich.With(ILogEventEnricher enricher)` )
- `Filter.With(params ILogEventFilter[] filters)` (with surrogate `Enrich.With(ILogEventFilter filter)` ) - _this one was already supported, but I added a unit test_
I also refactored a bit the part about *surrogate* configuration methods. There is now less code, and it is more …
> Add support and tests for more configuration methods

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
- test/TestDummies/DummyConfigurationSink.cs
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
fixes #143 where we are trying to read a subsection of config section passed as parameter
This is a regression introduced in v3.0.0
The `ConfigurationReader` had several constructor overloads, one of them accepting a `IConfigurationSection` instead of a `IConfiguration`... but the `IConfigurationSection` one was not being invoked by the `ReadFrom.ConfigSection()` extension methods.
Making that constructor `public` allows the section to be passed, but it also means the `ConfigurationReader` no longer has access to the *full* `Configuration` when that overload is used, so the behavior of *Serilog.Settings.Configuration* with config methods accepting `IConfiguration` parameters may be subtly broken. 
I am wondering if to properly solve that we should : 
- mark `ReadFrom.ConfigSection` as …
> Do not access "Serilog" sub-section when calling ReadFrom.ConfigSection / properly populate `IConfiguration` in configuration methods

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
In that case, the default value of the param will be passed
This PR completed the parts I missed in https://github.com/serilog/serilog-settings-configuration/pull/144 
Based on comment https://github.com/serilog/serilog-settings-configuration/issues/148#issuecomment-430221384 by @MV10 , an edge case was not tested ... it is now covered and fixed !
> No longer throw when calling a method with optional IConfiguration param

- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
Fixes [#81](https://github.com/serilog/serilog-settings-configuration/issues/81)
> Support simple type names for Serilog types (fixes #81)

- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/DynamicLevelChangeTests.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/JsonStringConfigSource.cs
- test/Serilog.Settings.Configuration.Tests/Support/ReloadableConfigurationSource.cs
- test/TestDummies/Console/DummyConsoleSink.cs
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
- dynamic level changes notifications for `LevelSwitch` section
- tests added
- NRE fix for `DummyConsoleSink`
- unused / unreachable related junk removed
- sample updated
Fixes [#99](https://github.com/serilog/serilog-settings-configuration/issues/99)
> Respect dynamic logging level changes for LevelSwitch section

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
`licenseUrl` is now deprecated so we use a `license expression`
Tracked in https://github.com/serilog/serilog/issues/1265
This properly populate the license information in the nuget package :
> Update Nuget package license format to new format

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/DllScanningAssemblyFinder.cs
- test/Serilog.Settings.Configuration.Tests/DllScanningAssemblyFinderTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- `ArgumentNullException` fix when `AppDomain.CurrentDomain.BaseDirectory` is null
- additional paths probing:  `AppDomainSetup.PrivateBinPath`, current assembly location path when `BaseDirectory` is null
Fixes [#150](https://github.com/serilog/serilog-settings-configuration/issues/150), [#157](https://github.com/serilog/serilog-settings-configuration/issues/157), [#122](https://github.com/serilog/serilog-settings-configuration/issues/122), [#156](https://github.com/serilog/serilog-settings-configuration/issues/156)
> DllScanningAssemblyFinder fixes (#157, #150, #122, #156)

- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
Fixes [#148](https://github.com/serilog/serilog-settings-configuration/issues/148)
> Added new ReadFrom.Configuration(...) overloads; Marked old as obsolete (#148)

- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
fixes [194](https://github.com/serilog/serilog-settings-configuration/issues/194)
> Show better error message for a missing interface parameter type

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- fixes [#197](https://github.com/serilog/serilog-settings-configuration/issues/197) to some extent for `netstandard2.0` target: the new package uses `System.Text.Json` instead of  `Newtonsoft.Json` to parse `.deps.json` files.
- no need to use workaround from [#218](https://github.com/serilog/serilog-settings-configuration/pull/218) since the new package doesn't bring .NET Core 1.x transitive dependencies, as `2.0.4` of `Microsoft.Extensions.DependencyModel` does.
> Update Microsoft.Extensions.DependencyModel to v3

- sample/Sample/Program.cs
- sample/Sample/Sample.csproj
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/IConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/SurrogateConfigurationMethods.cs
Base feature reference:
https://github.com/serilog/serilog/pull/1316
OOB will support `.Enrich.AtLevel(..)` and in combination with the latest `Serilog.Filters.Expressions` will support `.Enrich.When(expression, ...)`.
> Support conditional/leveled enrichers from Serilog 2.9+

- .editorconfig
- .vscode/launch.json
- .vscode/tasks.json
- CHANGES.md
- Directory.Build.props
- README.md
- sample/Sample/Sample.csproj
- sample/Sample/appsettings.json
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/TestDummies/TestDummies.csproj
* Fixes #137, #152, #154.
* improvements for making user contribution story (grab, build / test / run) easier under Linux environment. Added VSCode config that points to Sample app.
[Readme.md](https://github.com/serilog/serilog-settings-configuration/blob/f6d60233003a883fbdc9ed3268ed0f9459a7e587/README.md) was restructured to:
1. Basic setup / config
2. Syntax description and features 
3. Arguments binding
4. Samples
> Documentation update

- .vscode/launch.json
- Build.ps1
- CHANGES.md
- README.md
- appveyor.yml
- sample/Sample/Sample.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/AssemblyFinder.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/DependencyContextAssemblyFinder.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/Serilog.Settings.Configuration.Tests/Support/Extensions.cs
- fixes [#239](https://github.com/serilog/serilog-settings-configuration/issues/239), [#237](https://github.com/serilog/serilog-settings-configuration/issues/237)
- added .net 5.0 tfm
- added `Serilog.Expressions` to the sample project
- documentation update
> Configuration assembly auto-discovery fixes

- CHANGES.md
- Directory.Build.props
- README.md
- sample/Sample/Program.cs
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ResolutionContext.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- fixes #231 , implements both [Option 2 and 3](https://github.com/serilog/serilog-settings-appsettings/issues/7#issuecomment-325889701) of the initial design
- update reference to Serilog 2.10.0
- documentation update
> make '$' sign optional for minimum level / filter switch declarations

- CHANGES.md
- README.md
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/TestDummies/DummyThreadIdEnricher.cs
- fixes #260 
- updated docs: fixes #262 , #252
> skip static constructor on binding for complex parameters types

- CHANGES.md
- README.md
> Readme update

- CHANGES.md
- README.md
- sample/Sample/Program.cs
- sample/Sample/Sample.csproj
- sample/Sample/appsettings.json
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ObjectArgumentValueTests.cs
- test/Serilog.Settings.Configuration.Tests/ObjectArgumentValueTests.json
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
Added support for constructor parameters (implementation of [second](https://github.com/serilog/serilog-settings-configuration/issues/276#issuecomment-902331271) design) including nested configurations and type binding that [StringArgumentValue](https://github.com/serilog/serilog-settings-configuration/blob/dev/src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs#L11) supports.
```json
"formatter": {
"type": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
"valueFormatter": {
"typeTagName": "customTypeTag"
}
},
"formatter": {
"type": "Serilog.Templates.ExpressionTemplate, Serilog.Expressions",
"template": "[{@t:HH:mm:ss} {@l:u3} {Coalesce(SourceContext, '<none>')}] {@m}\n{@x}",
"formatProvider": …
```
> Support of constructor parameters

- CHANGES.md
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/StaticAccessorClasses.cs
> static member access for parameters of concrete types

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/DllScanningAssemblyFinderTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
- test/TestDummies/DummyThreadIdEnricher.cs
The `serilog-settings-configuration.sln.DotSettings` file defines many custom inspection severities as error rendering the solution with many red squiggly lines when opened in Rider or in Visual Studio with ReSharper.
> Fix ReSharper/Rider inspection warnings

- Build.ps1
- Directory.Build.props
- appveyor.yml
- sample/Sample/Sample.csproj
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/DllScanningAssemblyFinder.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/DllScanningAssemblyFinderTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
- test/TestDummies/TestDummies.csproj
* Add .NET 6 target framework instead
* Update tests and sample dependencies
* Simplify conditional package references in all projects
* Remove the custom `PRIVATE_BIN` define, use the built-in `NETFRAMEWORK` instead
* Also use the Visual Studio 2022 image on AppVeyor because VS 2022 is required for the .NET 6 SDK
* Add a reference to `Microsoft.TestPlatform.ObjectModel` so that `dotnet test` also works on Linux and macOS for the .NET Framework targets
* Depend on Microsoft.Extensions.Configuration.Binder: there's no need to depend on Microsoft.Extensions.Options.ConfigurationExtensions, taking a dependency on Microsoft.Extensions.Configuration.Binder is enough for what Serilog.Settings.Configuration needs to do.
> Remove out of support target frameworks

- appveyor.yml
Seems we've been publishing the package (first-in-wins) from both build configurations. No harm done but think this needs fixing for #299
> Publish only from the one build configuration

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/ConfigurationReaderTestHelpers.cs
- test/Serilog.Settings.Configuration.Tests/Support/Extensions.cs
A partial fix for minimumlevel not being correctly overriden by higher priority providers.
The fix only works for the .NET 4.6.1+ and .NET Standard builds as the IConfigurationRoot interface did not have Providers in .NET 4.5.1. 
I understand this is more of an annoyance than a real issue, but it's easy to miss.
> Minimumlevel partial fix with IConfigurationRoot.Providers

- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/StaticAccessorClasses.cs
> Add support for delegate type values through StringArgumentValue #259

- README.md
GitHub markdown syntax highlighting is awful for invalid/incomplete JSON, e.g.:
This PR is a "quick fix" - YAML is a subset of JSON, but the highlighter is more forgiving :-)
> Mark partial and invalid JSON code snippets as YAML

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
Support for .NET Framework 4, 4.5, and 4.5.1 [ended on January 12, 2016](https://learn.microsoft.com/en-GB/lifecycle/faq/dotnet-framework), that was 7 years ago!
Also bump Microsoft.Extensions.Configuration.Binder and Microsoft.Extensions.DependencyModel to version 6.0.0 since version 2.0.0 and 3.0.0 respectively have been deprecated as part of the [.NET Package Deprecation effort](https://github.com/dotnet/announcements/issues/217).
Finally, this change allows to remove all conditional compilation.
Note that removing a target framework is a breaking change so it will require a major version bump, i.e. 4.0.0.
> Drop support for .NET Framework 4.5.1

- README.md
- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReaderOptions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ResolutionContext.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
- test/TestDummies/DummyLoggerConfigurationExtensions.cs
- test/TestDummies/DummyPolicy.cs
Also introduce a new `ConfigurationContext` class to avoid `ReadFrom.Configuration()` methods exponential growth when adding new options.
All _older_ `Configuration()` methods go through the newly introduced `Configuration(LoggerSettingsConfiguration, IConfiguration, ConfigurationContext)` method that takes an `ConfigurationContext` instance.
Older methods explicitly set the `FormatProvider` option to `null` in order to preserve backward compatibility.
By using the new `Configuration()` method, users opt into the new default of having the invariant culture as the format provider.
Note: the `= null` default value in the `Configuration()` method taking a `DependencyContext` has been removed in order to make sure the CS0121 compilation does not occur:
> [CS0121] The call is ambiguous between …
> Add support for IFormatProvider used to convert string to other types

- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/DynamicLevelChangeTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/ConfigurationReaderTestHelpers.cs
In general for better readability.
> Use raw string literals

- README.md
- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReaderOptions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ResolutionContext.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
> Add a callback on the reader options to expose the log level switches

- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
> Allow configuration from contents of Serilog section

- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/AssemblyFinder.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ObjectArgumentValueTests.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
Not sure why they did not show up as warnings then as errors (since TreatWarningsAsErrors is true)
> Fix some nullable reference type issues

- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/DynamicLevelChangeTests.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
- test/Serilog.Settings.Configuration.Tests/Support/ConfigurationReaderTestHelpers.cs
- test/Serilog.Settings.Configuration.Tests/Support/Extensions.cs
- test/Serilog.Settings.Configuration.Tests/Support/JsonStringConfigSource.cs
So that we can get rid of the `ToValidJson` extension method.
Now that raw string literals have been introduced (in #354) having valid _readable_ JSON in strings for tests becomes easy. There is no need to escape quotes anymore with either `\"` or `""`.
This will also make it easier for newcomers to understand the tests at first glance. I had my WTF moment when I first saw JSON with single quotes. 🤔
> Make all JSON strings valid in tests

- src/Serilog.Settings.Configuration/Settings/Configuration/Assemblies/DllScanningAssemblyFinder.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/LoggingFilterSwitchProxy.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
Discovered by temporarily adding a net6.0 target framework which has better nullable reference type annotations.
> Add more nullable type reference safeties

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
List candidate methods only if there are any. Discovered this weird log while working on #353:
> Unable to find a method called WithThreadName. Candidate methods are:
> Improve SelfLog when a configuration method is not found

- README.md
Fix on the sample that wouldn't allow code to run by just copying it
> Added missing closing bracket on Complex parameter value binding summary

- README.md
- sample/Sample/CustomFilter.cs
- sample/Sample/CustomPolicy.cs
- sample/Sample/LoginData.cs
- sample/Sample/Program.cs
- sample/Sample/Sample.csproj
- src/Serilog.Settings.Configuration/ConfigurationLoggerConfigurationExtensions.cs
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationReaderTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/Serilog.Settings.Configuration.Tests/Support/ConfigurationReaderTestHelpers.cs
- test/Serilog.Settings.Configuration.Tests/Support/Extensions.cs
- test/Serilog.Settings.Configuration.Tests/Support/JsonStringConfigSource.cs
- test/Serilog.Settings.Configuration.Tests/Support/ReloadableConfigurationSource.cs
See also: https://github.com/serilog/serilog-extensions-logging/pull/222, https://github.com/serilog/serilog-extensions-hosting/pull/71, https://github.com/serilog/serilog-aspnetcore/pull/325
Unfortunately we've had some maintainability problems given the wide spread of target frameworks and dependencies across the Serilog sub-projects.
My aim's to kick through some RTM versions of all of these packages, pinned to their latest Microsoft.Extensions.* counterparts, ASAP.
I know we have https://github.com/serilog/serilog-settings-configuration/pull/343 open here (I've also held up the works there), my proposal is that we "rip the Band-Aid off" and merge this, then merge the release PR as v7.
Note that targeting v7 of the Microsoft.Extensions.* packages doesn't mean dropping earlier TFMs - …
> v7.0 - pin to MEC v7, including matching target frameworks

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
Use a HashSet instead of a Dictionary keyed by the assembly full name. If an assembly is loaded twice with the same AssemblyName it will be the same instance so a HashSet (without even a custom IEqualityComparer<Assembly>) is the perfect solution.
Also, Assembly.Load can throw many exceptions but won't return null.
This was initially introduced in 74402f836148f746f05a06f87cd8b15fee387155 but merged incorrectly in ac1b8c863307ceb598fbd6457ce9714ff2d1bde3.
> Simplify loading assemblies

- README.md
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReaderOptions.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ILoggingFilterSwitch.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/LoggingFilterSwitchProxy.cs
- src/Serilog.Settings.Configuration/Settings/Configuration/ResolutionContext.cs
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.approved.txt
Just like it was done for log level switches in #352.
> Add a callback on the reader options to expose the log filter switches

- test/Serilog.Settings.Configuration.Tests/Support/TestApp.cs
Was getting this exception because of assembly version mismatch:
> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Automatically generating binding redirects fixes the issue.
> Fix tests on .NET Framework 4.8 (really)

- Build.ps1
Use `throw` to exit when a `dotnet` command fails so that errors are properly reported on AppVeyor.
See also #372
> Fix build script

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/PublishSingleFileTests.cs
- test/TestApp/Program.cs
> Throw for missing configured assemblies only when required

- global.json
- sample/Sample/Sample.csproj
- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
- test/Serilog.Settings.Configuration.Tests/ConfigurationSettingsTests.cs
- test/Serilog.Settings.Configuration.Tests/DllScanningAssemblyFinderTests.cs
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
- test/TestApp/TestApp.csproj
Working my way through these in preparation for RTM in a couple of weeks.
I tried to keep this one as additive/nondestructive as possible, given all the quirks this project has to deal with across the supported TFMs :-)
> .NET 8 RC2

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
* Add `PackageProjectUrl`
* Add `PackageReleaseNotes` (points to https://github.com/serilog/serilog-settings-configuration/releases since CHANGES.md seems not maintained anymore)
* Add the README to the NuGet package (see https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)
> Improve NuGet packaging metadata

- .gitignore
- Build.ps1
- global.json
- test/Serilog.Settings.Configuration.Tests/Serilog.Settings.Configuration.Tests.csproj
This reduces the tests execution time in half. On my machine: 76 seconds when run in parallel vs 144 seconds when run serially.
The fix introduced in 41bc33d4bc7b03c920102ddaba195e96d152fb5f (running `dotnet test` on the csproj rather then on the built dlls) was problematic for two reasons.
1. It rebuilds `Serilog.Settings.Configuration.Tests.csproj` in Debug instead of Release and it's unnecessary since it was previously built.
2. It doesn't run tests in parallel anymore, increasing the total tests execution time.
The _right_ fix was to disable deterministic source paths for the test project with `<DeterministicSourcePaths>false</DeterministicSourcePaths>`. This way, the `[CallerFilePath]` attribute works as expected with absolute paths on the current machine instead of being substituted …
> Restore parallel tests execution

- src/Serilog.Settings.Configuration/Settings/Configuration/ObjectArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/ObjectArgumentValueTests.cs
Support collections and arrays as constructor arguments.
Closes #314
> Support collections as constructor arguments

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
Updates the transitive dependency on System.Text.Json to 8.0.4 to fix https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
refs #425
> Update Microsoft.Extensions.DependencyModel to 8.0.1

- src/Serilog.Settings.Configuration/Settings/Configuration/StringArgumentValue.cs
- test/Serilog.Settings.Configuration.Tests/StringArgumentValueTests.cs
All other enum parsing performed in the ConfigurationReader is also case insensitive.
Fixes #431
> Make string to enum conversion case insensitive

- src/Serilog.Settings.Configuration/Settings/Configuration/ConfigurationReader.cs
- test/Serilog.Settings.Configuration.Tests/LoggerConfigurationExtensionsTests.cs
Use value from `Serilog:MinimumLevel:Default` if value from `Serilog:MinimumLevel` is an empty string.
Fixes #332
> Prefer "MinimumLevel:Default" value if "MinimumLevel" value returns empty string

- src/Serilog.Settings.Configuration/Serilog.Settings.Configuration.csproj
It's CVE Tuesday again, and Microsoft have released a version 8.0.5 of System.Text.Json to fix https://github.com/advisories/GHSA-8g4q-xg66-9fp4 and an 8.0.2 of Microsoft.Extensions.DependencyModel that updates the System.Text.Json dependency to 8.0.5
> Update Microsoft.Extensions.DependencyModel to 8.0.2
